spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
server:
  port: 8088
  servlet:
    context-path: /api
xw:
  api:
    client:
      access-key: f56f7a684cd6431566c9e3bb9857d4f6
      secret-key: 20230bdde9035f5642a9b85a2daf1d4d
      #  本地测试增加修改
      host: http://localhost:8090/api
